### PR TITLE
Add null safety support

### PR DESCRIPTION
**Pull request by 6h4n3m**
Hey,

So as discussed, I've taken care of the changes necessary to support null safety for Flutter 2.0 and Dart version from 2.12 and above.

Changes made:
1) Bumped SDK restriction from 2.7.0 to 2.12.0 (new minimum).
2) Removed the meta package dependency since the `@required` annotation has been replaced and is not needed for named parameters anymore.
3) Added the `required` modifier to any required parameters in widgets and/or functions.
4) Changed the types of any optional named parameters to be nullable (ex. from `String` to `String?`).
5) Removed unnecessary not null asserts for required parameters as package users cannot send nullable values for these anymore.
6) Replaced the [DynamicTheme ](https://pub.dev/packages/dynamic_theme) dependency with the actively maintained [AdaptiveTheme](https://pub.dev/packages/adaptive_theme/versions/2.0.0-nullsafety.1) in order to make sure the package supports sound null safety and is not in mixed mode (ie. depends on packages with no null safety).
7) Replaced deprecated widget FlatButton with the replacement ElevatedButton where applicable (no changes to api surface of the package were made).

I ran the example app and everything works smoothly including theme switching.

You'd probably need to bump this into a new major version since it requires and SDK upgrade on the user's part.

Resolves codegrue/flutter_material_pickers#25

### CODE REVIEW

**Comment by 6h4n3m** [comment]
I think the CodeFactor issues are because the service doesn't support Dart null safety features yet... the two errors found make no sense.

**Review by codegrue — APPROVED** [review]

**Comment by Joseph-Nathan** [comment]
how can i used this ?
should i change all docs ?

**Comment by 6h4n3m** [comment]
> how can i used this ?
> should i change all docs ?

Version 2.0.0 is not on Pub yet due to some breaking changes in theming some picker widgets in Flutter 2.0 , @codegrue is still taking care of these.

In the meantime, you can depend on Master by doing something like this:
```
dependencies:
  flutter_material_pickers:
    git:
      url: git://github.com:codegrue/flutter_material_pickers.git
```
I would recommend that you hold off on doing this though, you might forget to change it back when the stable version hits Pub or there might be some breaking changes introduced into Master at any point.

**Comment by codegrue** [comment]
If you guys could test that would be great. Timepicker is as good as it gets without the Flutter team making some changes. I plan to publish on Monday.

**Comment by 6h4n3m** [comment]
I'll pull upstream and let you know if I find anything.

**Pull request merged**
